name: Load Image from MinIO

on:
  pull_request:
    branches:
      - main

env:
  MINIO_URL: ${{ secrets.MINIO_URL }}
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  FILE_PATH: ${{ secrets.FILE_PATH }}
  LOCAL_PATH: ${{ secrets.LOCAL_PATH }}
  ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  HASH_STRING: ${{ secrets.HASH_STRING }}

jobs:
  downloading:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install MinIO client
        run: |
          sudo apt-get update
          sudo apt install curl -y
          curl https://dl.min.io/client/mc/release/linux-amd64/mc --create-dirs -o $HOME/minio-binaries/mc
          chmod +x $HOME/minio-binaries/mc
          export PATH=$PATH:$HOME/minio-binaries/

      - name: Configure MinIO client
        run: |
          $HOME/minio-binaries/mc alias set myminio $MINIO_URL $ACCESS_KEY $SECRET_KEY

      - name: Download file from MinIO
        run: |
          $HOME/minio-binaries/mc cp myminio/$BUCKET_NAME/$FILE_PATH $LOCAL_PATH

      - name: Verify file exists
        run: |
          ls -l $LOCAL_PATH
          
      - name: Show MD5 hash of the file
        run: |
          md5sum $LOCAL_PATH
      
      - name: Check MD5 hash
        run: |
          echo "$HASH_STRING  $LOCAL_PATH" | md5sum -c -
